namespace CcTalk;

/// <summary>
/// Enumerates possible error codes reported by a CcTalk coin acceptor device.
/// </summary>
public enum CcTalkCoinAcceptorError
{
    RejectCoin = 1,
    InhibitedCoin = 2,
    MultipleWindow = 3,
    WakeUpTimeout = 4,
    ValidationTimeout = 5,
    CreditSensorTimeout = 6,
    SorterOptoTimeout = 7,
    SecondCloseCoinError = 8,
    AcceptGateNotReady = 9,
    CreditSensorNotReady = 10,
    SorterNotReady = 11,
    RejectCoinNotCleared = 12,
    ValidationSensorNotReady = 13,
    CreditSensorBlocked = 14,
    SorterOptoBlocked = 15,
    CreditSequenceError = 16,
    CoinGoingBackwards = 17,
    CoinTooFastCreditSensor = 18,
    CoinTooSlowCreditSensor = 19,
    CoinOnStringActive = 20,
    DCEOptoTimeout = 21,
    DCEOptoNotSeen = 22,
    CreditSensorReachedEarly = 23,
    RejectCoinRepeatedly = 24,
    RejectSlug = 25,
    RejectSensorBlocked = 26,
    GamesOverload = 27,
    MaxCoinMeterPulsesExceeded = 28,
    AcceptGateOpenNotClosed = 29,
    AcceptGateClosedNotOpen = 30,
    ManifoldOptoTimeout = 31,
    ManifoldOptoBlocked = 32,
    ManifoldNotReady = 33,
    SecurityStatusChanged = 34,
    MotorException = 35,
    SwallowedCoin = 36,
    CoinTooFastValidationSensor = 37,
    CoinTooSlowValidationSensor = 38,
    CoinIncorrectlySorted = 39,
    ExternalLightAttack = 40,
    InhibitedCoinType1 = 128,
    InhibitedCoinType2 = 129,
    InhibitedCoinType3 = 130,
    InhibitedCoinType4 = 131,
    InhibitedCoinType5 = 132,
    InhibitedCoinType6 = 133,
    InhibitedCoinType7 = 134,
    InhibitedCoinType8 = 135,
    InhibitedCoinType9 = 136,
    InhibitedCoinType10 = 137,
    InhibitedCoinType11 = 138,
    InhibitedCoinType12 = 139,
    InhibitedCoinType13 = 140,
    InhibitedCoinType14 = 141,
    InhibitedCoinType15 = 142,
    InhibitedCoinType16 = 143,
    DataBlockRequest = 253,
    FlightDeckOpen = 254,
    UnspecifiedAlarm = 255
}